  CREATE TABLE USER (
      ID VARCHAR (255) NOT NULL,
      FIRSTNAME VARCHAR(255) NOT NULL,
      LASTNAME VARCHAR(255) NOT NULL,
      USERNAME VARCHAR(255) NOT NULL,
      EMAIL VARCHAR(255) NOT NULL,
      PRIMARY KEY (ID)

  );